export const DOCUMENT_TEMPLATES = [
  'Vision Document',
  'Problem Statement',
  'Business Case',
  'Objectifs Initiaux',
  'Project Charter',
  'PRD',
  'Roadmap',
  'Technical Specification',
  'Decision Log',
  'OKRs / Metrics Document',
  'UX Research Document',
  'API Specification',
  'Security Review Document',
  'Performance Plan',
  'Go-To-Market Plan',
  'Risk Management Document',
  'Compliance Documentation',
  'Legal Review Document',
  'Architecture Review Board Document',
  'Incident Report',
  'Post-Mortem Document',
  'SLA Document',
  'Governance Documentation',
] as const;
